server:
  port: 8091

# 应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    # 跨域，开发阶段可以设置为 * 不限制
    cross-origin: '*'
    # 访问频次限制
    limit-count: 10
    # 白名单，不做频次拦截【微信的openai】oxfA9w8-23yvwTmo2ombz0E4zJv4,oQESu6Jve0sJhFlt6QuCUr6xTA6k
    white-list: oQESu6Jve0sJhFlt6QuCUr6xTA6k

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

# ChatGPT SDK Config
chatgpt:
  sdk:
    config:
      # 官网地址 https://api.openai.com/
      api-host: https://api.bianxie.ai/
      # 官网申请 https://platform.openai.com/account/api-keys
      api-key: sk-5PxigqRxv6Ms5BgR95Fc824057564701BfCc81Fc09854eF7

# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_5cced615072a
    appid: wx69431dae41e821eb
    token: admin

# 数据库配置；SpringBoot 默认连接池为 HikariDataSource
spring:
  datasource:
    username: root
    password: Zy29824741
    url: jdbc:mysql://localhost:3306/openai?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    pool-name: Retail_HikariCP
    minimum-idle: 15 #最小空闲连接数量
    idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
    maximum-pool-size: 25 #连接池最大连接数，默认是10
    auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
    max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
    connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
    connection-test-query: SELECT 1
  type: com.zaxxer.hikari.HikariDataSource

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml
# application-dev.yml
# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000140612588
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQChbk0wkLQ5x7HprDJATmbWFGIyxvHhoj9UARz5vJc3zIuJRvbyWZEctZqdMopM/LZz4x9r8r4p2jPILfuN+DWjw53TfnvU3DWxFTgF6nGc4oCLGh+T0zTZAoe9AFLBUWCak6xV50fWloUknXWfAO1eiqrcUYCInPkSGcsUcmf/VGNjYmCGFpXG3eDg05HY8h7mm3hCpiAswqFb+2YenX4Jykgk8Cd5HQR/zvzIyS1Vv2JMBRL7mnzhKs4csruaRfSU0i9mHy22cE17TIeW4cDWXnU3a1MqAy3TmAnPaYsF1MIP9/gIJ7vcudaYmhcDwBwvRsSRsKhdNaVesqVLLHhZAgMBAAECggEBAJ4oQtfh7bDuRRB69ICsT3ROZCb7Yt985i6XKJxEeKLic5L7Q9YMim9mPSTl7zmeHeNMEezg1g6LCVCGPH7LP0JC1M3wjcHuPWxRLaIeH1FlWCrwXR+nPY+fOv2g43MjF1Jae+1tuqQytB87ZZFyhxypHtzbvOIbaKqjOqO9ssYjgZ4d/i3oXKru96kzg/PCQq36F3dzWkvY4rI6aw7VzXNOFzzeIxtOu5EwX1KxcsSEncULmjOyI2FyZ/AcEbnMNoLckDOvbpwiJtWQUMStZ9xBo4HVPGj0rGjF2uHEYJ086foP2i3Pu8Fym2OnGNjtjP0jPOUp2QCMcHVhS461eQECgYEA9tfQQd3UKtNdM2Qt899dsdwrCurYmNnlqsY2BUdxwANXtF5HTyBUHe8bwA1z6ZAsakYdX49hLsh459/EfF/yk3U21i6BfdgAh4jcKIbAP/BIqxqtYCeJ3ILritoIYxAl3JWiLb6QgSXn2/MpJllDsDb/gzmWjZ5NCYVRtrhNH60CgYEAp2tbZoEQjbR+Le7KkHxUeuIB6qAqFbZNoHwCoUxKcP25yqhmgDYjVMyeHqxWtc8tZtswvxl/1OBHdK1RPvMDgn2f/j92w6mMqNOpkXB3EDPPfazAQLditrEeiuvQRf/mXgSpiHZ2FTMH9dY7j0EjiPPwhWCfkOmAHMRR79l8oN0CgYEA9sdr/W2439fQJcDR8C4vjdF/drqzMJ0nb0QaXcy/fCfbVweqYwD/F64lICxS5f6taNIQK6k8j3j851RfK7kA20skN5zm+NkqLlY1RI7zRPkErYtOKgNdYIfC1F6GZAOQ1qcCLJmH/pXW556CVUSI13MkoBzC13KbshkHSJWZBUECgYBiSELi3PejyIaeXmVqBqLtdIode6LZFiliAgrlN80nobuU/eEWeTGqkWhtp0xL9PC5RgnK1aRWisdH9osQgkbYLvlin00QNhON9JvB9pze1RuEsoo2M7Huf/HnKeIdhclt/hysMKbHcSrGJdrXES1UM6hKFFv4DSuZN6LGRA3GvQKBgF+A1+bNWR+3otT0qyn5IycCaHV3m9lQb5U+7okJdP+AflG6A3CbccsLgG9EDXW9kAMXX0BMjD2rkirTC0nuDClmttPbCUGGCQcLXwzkvo+R7ce++jSkcQLc9rfWKFNYRRbdleg6c7tiZFOgFszsK23csleZKZz4kgha2A/HnpMC
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv9VXe/wT8L7SLHNjqWosCCuud0pkyhjHY889ebXi68EdW+X3tukGOSTyNF3FS7dC+wtp32fA3fOiydyGxiTfE6uR6IriaNltLenuLn0CoO8JgT8vZtSw2NTPfYak29kWPWG4PQY8VLapSYOqtQnAChDRQoeSAfK+fiZcunXo4z1TGOiRBqgm+2MoVNcpoqU1ZnjohTAxDeJV8a3SXmgCw1xrSKzJTi0gBgtIYfWUMBNKVIxzD0PZvonvGVuHhvI+rgsXs2IUVIVnsMnB0Et13SUU8LXQrXMxFcFrNXsSlUubXm3Oj7RZOPIUiu37h4lEgryicOoVWbkJU1b6CcAFqQIDAQAB
  #支付回调地址
  notify_url: http://jkbnpi.natappfree.cc/api/v1/sale/pay_notify
  return_url: https://cn.bing.com
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml